import type { Quest } from "../api/client";

export const MOCK_QUESTS: Quest[] = [
  {
    id: "quest-1",
    title: "JinkFi Genesis Campaign",
    description: "Be among the first to explore JinkFi DEX. Complete social, onchain and quiz tasks to earn exclusive genesis rewards.",
    projectName: "JinkFi",
    bannerUrl: "",
    startDate: new Date(Date.now() - 86400000 * 2).toISOString(),
    endDate:   new Date(Date.now() + 86400000 * 14).toISOString(),
    totalParticipants: 4821,
    totalPoints: 500,
    featured: true,
    tags: ["DeFi", "DEX", "Genesis"],
    rewards: [
      { id: "r1", type: "token", symbol: "JINK", amount: "1000", label: "1,000 JINK" },
      { id: "r2", type: "nft",   label: "Genesis OG Badge NFT" },
    ],
    tasks: [
      { id: "t1", type: "twitter_follow", title: "Follow @JinkFi on X",      description: "Follow our official X account to stay updated.", points: 50,  required: true,  link: "https://x.com" },
      { id: "t2", type: "twitter_retweet",title: "Retweet the launch post",   description: "Retweet our launch announcement post.",           points: 75,  required: false, link: "https://x.com" },
      { id: "t3", type: "discord_join",   title: "Join JinkFi Discord",       description: "Join our community Discord server.",              points: 50,  required: true,  link: "https://discord.com" },
      { id: "t4", type: "quiz",           title: "What is concentrated liquidity?", description: "Answer a question about Uniswap V3.",       points: 100, required: false, metadata: { options: ["Providing liquidity across the full price range", "Providing liquidity within a custom price range", "Locking tokens for a fixed period", "A type of yield farming strategy"], answer: "Providing liquidity within a custom price range" } },
      { id: "t5", type: "onchain",        title: "Make your first swap",      description: "Complete any token swap on JinkFi DEX.",          points: 150, required: false },
      { id: "t6", type: "onchain",        title: "Add liquidity",             description: "Add liquidity to any pool on JinkFi.",            points: 75,  required: false },
    ],
  },
  {
    id: "quest-2",
    title: "Perps Pioneer",
    description: "Explore the JinkFi perpetuals trading platform. Open your first position and trade like a pro.",
    projectName: "JinkFi Perps",
    bannerUrl: "",
    startDate: new Date(Date.now() - 86400000).toISOString(),
    endDate:   new Date(Date.now() + 86400000 * 7).toISOString(),
    totalParticipants: 1203,
    totalPoints: 350,
    featured: true,
    tags: ["Perps", "Trading", "Leverage"],
    rewards: [
      { id: "r3", type: "token", symbol: "JINK", amount: "500", label: "500 JINK" },
    ],
    tasks: [
      { id: "t7",  type: "quiz",    title: "What is a perpetual contract?",  description: "Test your knowledge of perpetual futures.",   points: 75,  required: false, metadata: { options: ["A futures contract with no expiry date", "A spot trading position", "A liquidity pool token", "An NFT smart contract"], answer: "A futures contract with no expiry date" } },
      { id: "t8",  type: "onchain", title: "Open a long position",           description: "Open any long position on JinkFi Perps.",     points: 150, required: true  },
      { id: "t9",  type: "onchain", title: "Open a short position",          description: "Open any short position on JinkFi Perps.",    points: 125, required: false },
    ],
  },
  {
    id: "quest-3",
    title: "Liquidity Provider Bootcamp",
    description: "Learn the difference between V2, V3 concentrated, and V4 hook-powered liquidity. Earn rewards for providing.",
    projectName: "JinkFi",
    bannerUrl: "",
    startDate: new Date(Date.now() - 86400000 * 5).toISOString(),
    endDate:   new Date(Date.now() + 86400000 * 21).toISOString(),
    totalParticipants: 872,
    totalPoints: 400,
    featured: false,
    tags: ["Liquidity", "V3", "V4", "Education"],
    rewards: [
      { id: "r4", type: "token", symbol: "JINK", amount: "750", label: "750 JINK" },
      { id: "r5", type: "nft",   label: "LP Master Badge" },
    ],
    tasks: [
      { id: "t10", type: "quiz",    title: "V2 vs V3 liquidity",            description: "What is the main advantage of V3 over V2?",    points: 75,  required: false, metadata: { options: ["V3 is cheaper to deploy", "V3 uses concentrated liquidity ranges", "V3 has lower gas fees", "V3 supports more tokens"], answer: "V3 uses concentrated liquidity ranges" } },
      { id: "t11", type: "onchain", title: "Add V2 liquidity",              description: "Add liquidity to a V2 pool.",                  points: 100, required: false },
      { id: "t12", type: "onchain", title: "Create a V3 position",          description: "Create a concentrated liquidity V3 position.", points: 150, required: false },
      { id: "t13", type: "twitter_follow", title: "Follow for LP tips",     description: "Follow our LP strategy account.",              points: 75,  required: false, link: "https://x.com" },
    ],
  },
  {
    id: "quest-4",
    title: "Token Locker Challenge",
    description: "Learn about token security by locking tokens with JinkFi Locker — the non-custodial lock protocol.",
    projectName: "JinkFi Locker",
    bannerUrl: "",
    startDate: new Date(Date.now() - 86400000 * 1).toISOString(),
    endDate:   new Date(Date.now() + 86400000 * 30).toISOString(),
    totalParticipants: 430,
    totalPoints: 250,
    featured: false,
    tags: ["Locker", "Security", "DeFi"],
    rewards: [
      { id: "r6", type: "token", symbol: "JINK", amount: "300", label: "300 JINK" },
    ],
    tasks: [
      { id: "t14", type: "onchain", title: "Lock any token",   description: "Lock any ERC-20 token using JinkFi Locker.", points: 150, required: true  },
      { id: "t15", type: "quiz",    title: "Why lock tokens?", description: "Understand the purpose of token locking.",   points: 100, required: false, metadata: { options: ["To earn yield", "To signal commitment and prevent rug pulls", "To swap tokens", "To farm rewards"], answer: "To signal commitment and prevent rug pulls" } },
    ],
  },
];
