/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as locker from "./locker";
export type { locker };
import type * as mocks from "./mocks";
export type { mocks };
export type { JinkFarm } from "./JinkFarm";
export type { TokenLocker } from "./TokenLocker";
