/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ITokenLockerManagerV1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "createLpLocker"
      | "createTokenLocker"
      | "creationEnabled"
      | "getLpData"
      | "getLpLockAddress"
      | "getLpLockData"
      | "getLpLockersForAddress"
      | "getTokenLockAddress"
      | "getTokenLockData"
      | "getTokenLockersForAddress"
      | "lpLockerCount"
      | "notifyLpLockerOwnerChange"
      | "notifyTokenLockerOwnerChange"
      | "setCreationEnabled"
      | "tokenLockerCount"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createLpLocker",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTokenLocker",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creationEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLpData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLpLockAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLpLockData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLpLockersForAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenLockAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenLockData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenLockersForAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lpLockerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "notifyLpLockerOwnerChange",
    values: [BigNumberish, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "notifyTokenLockerOwnerChange",
    values: [BigNumberish, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreationEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenLockerCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createLpLocker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTokenLocker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creationEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLpData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLpLockAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLpLockData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLpLockersForAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenLockAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenLockData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenLockersForAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lpLockerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifyLpLockerOwnerChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifyTokenLockerOwnerChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreationEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenLockerCount",
    data: BytesLike
  ): Result;
}

export interface ITokenLockerManagerV1 extends BaseContract {
  connect(runner?: ContractRunner | null): ITokenLockerManagerV1;
  waitForDeployment(): Promise<this>;

  interface: ITokenLockerManagerV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createLpLocker: TypedContractMethod<
    [
      tokenAddress_: AddressLike,
      amount_: BigNumberish,
      unlockTime_: BigNumberish
    ],
    [void],
    "payable"
  >;

  createTokenLocker: TypedContractMethod<
    [
      tokenAddress_: AddressLike,
      amount_: BigNumberish,
      unlockTime_: BigNumberish
    ],
    [void],
    "payable"
  >;

  creationEnabled: TypedContractMethod<[], [boolean], "view">;

  getLpData: TypedContractMethod<
    [id_: BigNumberish],
    [
      [boolean, bigint, string, string, bigint, bigint, bigint, bigint] & {
        hasLpData: boolean;
        id: bigint;
        token0: string;
        token1: string;
        balance0: bigint;
        balance1: bigint;
        price0: bigint;
        price1: bigint;
      }
    ],
    "view"
  >;

  getLpLockAddress: TypedContractMethod<[id_: BigNumberish], [string], "view">;

  getLpLockData: TypedContractMethod<
    [id_: BigNumberish],
    [
      [
        boolean,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isLpToken: boolean;
        id: bigint;
        contractAddress: string;
        lockOwner: string;
        token: string;
        createdBy: string;
        createdAt: bigint;
        blockTime: bigint;
        unlockTime: bigint;
        balance: bigint;
        totalSupply: bigint;
      }
    ],
    "view"
  >;

  getLpLockersForAddress: TypedContractMethod<
    [address_: AddressLike],
    [bigint[]],
    "view"
  >;

  getTokenLockAddress: TypedContractMethod<
    [id_: BigNumberish],
    [string],
    "view"
  >;

  getTokenLockData: TypedContractMethod<
    [id_: BigNumberish],
    [
      [
        boolean,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isLpToken: boolean;
        id: bigint;
        contractAddress: string;
        lockOwner: string;
        token: string;
        createdBy: string;
        createdAt: bigint;
        blockTime: bigint;
        unlockTime: bigint;
        balance: bigint;
        totalSupply: bigint;
      }
    ],
    "view"
  >;

  getTokenLockersForAddress: TypedContractMethod<
    [address_: AddressLike],
    [bigint[]],
    "view"
  >;

  lpLockerCount: TypedContractMethod<[], [bigint], "view">;

  notifyLpLockerOwnerChange: TypedContractMethod<
    [
      id_: BigNumberish,
      newOwner_: AddressLike,
      previousOwner_: AddressLike,
      createdBy_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  notifyTokenLockerOwnerChange: TypedContractMethod<
    [
      id_: BigNumberish,
      newOwner_: AddressLike,
      previousOwner_: AddressLike,
      createdBy_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  setCreationEnabled: TypedContractMethod<
    [value_: boolean],
    [void],
    "nonpayable"
  >;

  tokenLockerCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createLpLocker"
  ): TypedContractMethod<
    [
      tokenAddress_: AddressLike,
      amount_: BigNumberish,
      unlockTime_: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createTokenLocker"
  ): TypedContractMethod<
    [
      tokenAddress_: AddressLike,
      amount_: BigNumberish,
      unlockTime_: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "creationEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getLpData"
  ): TypedContractMethod<
    [id_: BigNumberish],
    [
      [boolean, bigint, string, string, bigint, bigint, bigint, bigint] & {
        hasLpData: boolean;
        id: bigint;
        token0: string;
        token1: string;
        balance0: bigint;
        balance1: bigint;
        price0: bigint;
        price1: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLpLockAddress"
  ): TypedContractMethod<[id_: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getLpLockData"
  ): TypedContractMethod<
    [id_: BigNumberish],
    [
      [
        boolean,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isLpToken: boolean;
        id: bigint;
        contractAddress: string;
        lockOwner: string;
        token: string;
        createdBy: string;
        createdAt: bigint;
        blockTime: bigint;
        unlockTime: bigint;
        balance: bigint;
        totalSupply: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLpLockersForAddress"
  ): TypedContractMethod<[address_: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTokenLockAddress"
  ): TypedContractMethod<[id_: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenLockData"
  ): TypedContractMethod<
    [id_: BigNumberish],
    [
      [
        boolean,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isLpToken: boolean;
        id: bigint;
        contractAddress: string;
        lockOwner: string;
        token: string;
        createdBy: string;
        createdAt: bigint;
        blockTime: bigint;
        unlockTime: bigint;
        balance: bigint;
        totalSupply: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenLockersForAddress"
  ): TypedContractMethod<[address_: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "lpLockerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "notifyLpLockerOwnerChange"
  ): TypedContractMethod<
    [
      id_: BigNumberish,
      newOwner_: AddressLike,
      previousOwner_: AddressLike,
      createdBy_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "notifyTokenLockerOwnerChange"
  ): TypedContractMethod<
    [
      id_: BigNumberish,
      newOwner_: AddressLike,
      previousOwner_: AddressLike,
      createdBy_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCreationEnabled"
  ): TypedContractMethod<[value_: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenLockerCount"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
