/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TokenLockerV1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "deposit"
      | "getIsLpToken"
      | "getLockData"
      | "getLpData"
      | "owner"
      | "transferOwnership"
      | "withdraw"
      | "withdrawEth"
      | "withdrawToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "Extended"
      | "OwnershipTransferred"
      | "Withdrew"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIsLpToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLockData",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getLpData", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawEth",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIsLpToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLockData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLpData", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExtendedEvent {
  export type InputTuple = [newUnlockTime: BigNumberish];
  export type OutputTuple = [newUnlockTime: bigint];
  export interface OutputObject {
    newUnlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrewEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenLockerV1 extends BaseContract {
  connect(runner?: ContractRunner | null): TokenLockerV1;
  waitForDeployment(): Promise<this>;

  interface: TokenLockerV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deposit: TypedContractMethod<
    [amount_: BigNumberish, newUnlockTime_: BigNumberish],
    [void],
    "nonpayable"
  >;

  getIsLpToken: TypedContractMethod<[], [boolean], "view">;

  getLockData: TypedContractMethod<
    [],
    [
      [
        boolean,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isLpToken: boolean;
        id: bigint;
        contractAddress: string;
        lockOwner: string;
        token: string;
        createdBy: string;
        createdAt: bigint;
        blockTime: bigint;
        unlockTime: bigint;
        balance: bigint;
        totalSupply: bigint;
      }
    ],
    "view"
  >;

  getLpData: TypedContractMethod<
    [],
    [
      [boolean, bigint, string, string, bigint, bigint, bigint, bigint] & {
        hasLpData: boolean;
        id: bigint;
        token0: string;
        token1: string;
        balance0: bigint;
        balance1: bigint;
        price0: bigint;
        price1: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner_: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  withdrawEth: TypedContractMethod<[], [void], "nonpayable">;

  withdrawToken: TypedContractMethod<
    [address_: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [amount_: BigNumberish, newUnlockTime_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getIsLpToken"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getLockData"
  ): TypedContractMethod<
    [],
    [
      [
        boolean,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isLpToken: boolean;
        id: bigint;
        contractAddress: string;
        lockOwner: string;
        token: string;
        createdBy: string;
        createdAt: bigint;
        blockTime: bigint;
        unlockTime: bigint;
        balance: bigint;
        totalSupply: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLpData"
  ): TypedContractMethod<
    [],
    [
      [boolean, bigint, string, string, bigint, bigint, bigint, bigint] & {
        hasLpData: boolean;
        id: bigint;
        token0: string;
        token1: string;
        balance0: bigint;
        balance1: bigint;
        price0: bigint;
        price1: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawEth"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<[address_: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Extended"
  ): TypedContractEvent<
    ExtendedEvent.InputTuple,
    ExtendedEvent.OutputTuple,
    ExtendedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Withdrew"
  ): TypedContractEvent<
    WithdrewEvent.InputTuple,
    WithdrewEvent.OutputTuple,
    WithdrewEvent.OutputObject
  >;

  filters: {
    "Deposited(uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Extended(uint40)": TypedContractEvent<
      ExtendedEvent.InputTuple,
      ExtendedEvent.OutputTuple,
      ExtendedEvent.OutputObject
    >;
    Extended: TypedContractEvent<
      ExtendedEvent.InputTuple,
      ExtendedEvent.OutputTuple,
      ExtendedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Withdrew()": TypedContractEvent<
      WithdrewEvent.InputTuple,
      WithdrewEvent.OutputTuple,
      WithdrewEvent.OutputObject
    >;
    Withdrew: TypedContractEvent<
      WithdrewEvent.InputTuple,
      WithdrewEvent.OutputTuple,
      WithdrewEvent.OutputObject
    >;
  };
}
