/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TokenLockerManagerV1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "LpLockerFee"
      | "TokenLockerFee"
      | "createLpLocker"
      | "createTokenLocker"
      | "creationEnabled"
      | "feeWallet"
      | "getLpData"
      | "getLpLockAddress"
      | "getLpLockData"
      | "getLpLockersForAddress"
      | "getTokenLockAddress"
      | "getTokenLockData"
      | "getTokenLockersForAddress"
      | "lpLockerCount"
      | "notifyLpLockerOwnerChange"
      | "notifyTokenLockerOwnerChange"
      | "owner"
      | "setCreationEnabled"
      | "setFeeWallet"
      | "setLpLockerFee"
      | "setTokenLockerFee"
      | "tokenLockerCount"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LpLockerCreated"
      | "OwnershipTransferred"
      | "TokenLockerCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LpLockerFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TokenLockerFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createLpLocker",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTokenLocker",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creationEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feeWallet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getLpData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLpLockAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLpLockData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLpLockersForAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenLockAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenLockData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenLockersForAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lpLockerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "notifyLpLockerOwnerChange",
    values: [BigNumberish, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "notifyTokenLockerOwnerChange",
    values: [BigNumberish, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setCreationEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLpLockerFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenLockerFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenLockerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "LpLockerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TokenLockerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createLpLocker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTokenLocker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creationEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeWallet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLpData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLpLockAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLpLockData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLpLockersForAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenLockAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenLockData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenLockersForAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lpLockerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifyLpLockerOwnerChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "notifyTokenLockerOwnerChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCreationEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLpLockerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenLockerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenLockerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace LpLockerCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    token: AddressLike,
    token0: AddressLike,
    token1: AddressLike,
    createdBy: AddressLike,
    balance: BigNumberish,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    token: string,
    token0: string,
    token1: string,
    createdBy: string,
    balance: bigint,
    unlockTime: bigint
  ];
  export interface OutputObject {
    id: bigint;
    token: string;
    token0: string;
    token1: string;
    createdBy: string;
    balance: bigint;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenLockerCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    token: AddressLike,
    createdBy: AddressLike,
    balance: BigNumberish,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    token: string,
    createdBy: string,
    balance: bigint,
    unlockTime: bigint
  ];
  export interface OutputObject {
    id: bigint;
    token: string;
    createdBy: string;
    balance: bigint;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenLockerManagerV1 extends BaseContract {
  connect(runner?: ContractRunner | null): TokenLockerManagerV1;
  waitForDeployment(): Promise<this>;

  interface: TokenLockerManagerV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LpLockerFee: TypedContractMethod<[], [bigint], "view">;

  TokenLockerFee: TypedContractMethod<[], [bigint], "view">;

  createLpLocker: TypedContractMethod<
    [lpAddress_: AddressLike, amount_: BigNumberish, unlockTime_: BigNumberish],
    [void],
    "payable"
  >;

  createTokenLocker: TypedContractMethod<
    [
      tokenAddress_: AddressLike,
      amount_: BigNumberish,
      unlockTime_: BigNumberish
    ],
    [void],
    "payable"
  >;

  creationEnabled: TypedContractMethod<[], [boolean], "view">;

  feeWallet: TypedContractMethod<[], [string], "view">;

  getLpData: TypedContractMethod<
    [id_: BigNumberish],
    [
      [boolean, bigint, string, string, bigint, bigint, bigint, bigint] & {
        hasLpData: boolean;
        id: bigint;
        token0: string;
        token1: string;
        balance0: bigint;
        balance1: bigint;
        price0: bigint;
        price1: bigint;
      }
    ],
    "view"
  >;

  getLpLockAddress: TypedContractMethod<[id_: BigNumberish], [string], "view">;

  getLpLockData: TypedContractMethod<
    [id_: BigNumberish],
    [
      [
        boolean,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isLpToken: boolean;
        id: bigint;
        contractAddress: string;
        lockOwner: string;
        token: string;
        createdBy: string;
        createdAt: bigint;
        blockTime: bigint;
        unlockTime: bigint;
        balance: bigint;
        totalSupply: bigint;
      }
    ],
    "view"
  >;

  getLpLockersForAddress: TypedContractMethod<
    [address_: AddressLike],
    [bigint[]],
    "view"
  >;

  getTokenLockAddress: TypedContractMethod<
    [id_: BigNumberish],
    [string],
    "view"
  >;

  getTokenLockData: TypedContractMethod<
    [id_: BigNumberish],
    [
      [
        boolean,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isLpToken: boolean;
        id: bigint;
        contractAddress: string;
        lockOwner: string;
        token: string;
        createdBy: string;
        createdAt: bigint;
        blockTime: bigint;
        unlockTime: bigint;
        balance: bigint;
        totalSupply: bigint;
      }
    ],
    "view"
  >;

  getTokenLockersForAddress: TypedContractMethod<
    [address_: AddressLike],
    [bigint[]],
    "view"
  >;

  lpLockerCount: TypedContractMethod<[], [bigint], "view">;

  notifyLpLockerOwnerChange: TypedContractMethod<
    [
      id_: BigNumberish,
      newOwner_: AddressLike,
      previousOwner_: AddressLike,
      createdBy_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  notifyTokenLockerOwnerChange: TypedContractMethod<
    [
      id_: BigNumberish,
      newOwner_: AddressLike,
      previousOwner_: AddressLike,
      createdBy_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setCreationEnabled: TypedContractMethod<
    [value_: boolean],
    [void],
    "nonpayable"
  >;

  setFeeWallet: TypedContractMethod<
    [_newWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setLpLockerFee: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenLockerFee: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenLockerCount: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner_: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LpLockerFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TokenLockerFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createLpLocker"
  ): TypedContractMethod<
    [lpAddress_: AddressLike, amount_: BigNumberish, unlockTime_: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createTokenLocker"
  ): TypedContractMethod<
    [
      tokenAddress_: AddressLike,
      amount_: BigNumberish,
      unlockTime_: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "creationEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "feeWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLpData"
  ): TypedContractMethod<
    [id_: BigNumberish],
    [
      [boolean, bigint, string, string, bigint, bigint, bigint, bigint] & {
        hasLpData: boolean;
        id: bigint;
        token0: string;
        token1: string;
        balance0: bigint;
        balance1: bigint;
        price0: bigint;
        price1: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLpLockAddress"
  ): TypedContractMethod<[id_: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getLpLockData"
  ): TypedContractMethod<
    [id_: BigNumberish],
    [
      [
        boolean,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isLpToken: boolean;
        id: bigint;
        contractAddress: string;
        lockOwner: string;
        token: string;
        createdBy: string;
        createdAt: bigint;
        blockTime: bigint;
        unlockTime: bigint;
        balance: bigint;
        totalSupply: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLpLockersForAddress"
  ): TypedContractMethod<[address_: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTokenLockAddress"
  ): TypedContractMethod<[id_: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenLockData"
  ): TypedContractMethod<
    [id_: BigNumberish],
    [
      [
        boolean,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isLpToken: boolean;
        id: bigint;
        contractAddress: string;
        lockOwner: string;
        token: string;
        createdBy: string;
        createdAt: bigint;
        blockTime: bigint;
        unlockTime: bigint;
        balance: bigint;
        totalSupply: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenLockersForAddress"
  ): TypedContractMethod<[address_: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "lpLockerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "notifyLpLockerOwnerChange"
  ): TypedContractMethod<
    [
      id_: BigNumberish,
      newOwner_: AddressLike,
      previousOwner_: AddressLike,
      createdBy_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "notifyTokenLockerOwnerChange"
  ): TypedContractMethod<
    [
      id_: BigNumberish,
      newOwner_: AddressLike,
      previousOwner_: AddressLike,
      createdBy_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setCreationEnabled"
  ): TypedContractMethod<[value_: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeWallet"
  ): TypedContractMethod<[_newWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLpLockerFee"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenLockerFee"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenLockerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner_: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "LpLockerCreated"
  ): TypedContractEvent<
    LpLockerCreatedEvent.InputTuple,
    LpLockerCreatedEvent.OutputTuple,
    LpLockerCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenLockerCreated"
  ): TypedContractEvent<
    TokenLockerCreatedEvent.InputTuple,
    TokenLockerCreatedEvent.OutputTuple,
    TokenLockerCreatedEvent.OutputObject
  >;

  filters: {
    "LpLockerCreated(uint40,address,address,address,address,uint256,uint40)": TypedContractEvent<
      LpLockerCreatedEvent.InputTuple,
      LpLockerCreatedEvent.OutputTuple,
      LpLockerCreatedEvent.OutputObject
    >;
    LpLockerCreated: TypedContractEvent<
      LpLockerCreatedEvent.InputTuple,
      LpLockerCreatedEvent.OutputTuple,
      LpLockerCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenLockerCreated(uint40,address,address,uint256,uint40)": TypedContractEvent<
      TokenLockerCreatedEvent.InputTuple,
      TokenLockerCreatedEvent.OutputTuple,
      TokenLockerCreatedEvent.OutputObject
    >;
    TokenLockerCreated: TypedContractEvent<
      TokenLockerCreatedEvent.InputTuple,
      TokenLockerCreatedEvent.OutputTuple,
      TokenLockerCreatedEvent.OutputObject
    >;
  };
}
