/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface UtilInterface extends Interface {
  getFunction(
    nameOrSignature: "getLpData" | "getTokenData" | "isLpToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getLpData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isLpToken",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getLpData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isLpToken", data: BytesLike): Result;
}

export interface Util extends BaseContract {
  connect(runner?: ContractRunner | null): Util;
  waitForDeployment(): Promise<this>;

  interface: UtilInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLpData: TypedContractMethod<
    [address_: AddressLike],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        token0: string;
        token1: string;
        balance0: bigint;
        balance1: bigint;
        price0: bigint;
        price1: bigint;
      }
    ],
    "view"
  >;

  getTokenData: TypedContractMethod<
    [address_: AddressLike],
    [
      [string, string, bigint, bigint, bigint] & {
        name: string;
        symbol: string;
        decimals: bigint;
        totalSupply: bigint;
        balance: bigint;
      }
    ],
    "view"
  >;

  isLpToken: TypedContractMethod<[address_: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLpData"
  ): TypedContractMethod<
    [address_: AddressLike],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        token0: string;
        token1: string;
        balance0: bigint;
        balance1: bigint;
        price0: bigint;
        price1: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenData"
  ): TypedContractMethod<
    [address_: AddressLike],
    [
      [string, string, bigint, bigint, bigint] & {
        name: string;
        symbol: string;
        decimals: bigint;
        totalSupply: bigint;
        balance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isLpToken"
  ): TypedContractMethod<[address_: AddressLike], [boolean], "view">;

  filters: {};
}
