/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITokenLockerManagerV1,
  ITokenLockerManagerV1Interface,
} from "../../../contracts/locker/ITokenLockerManagerV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
      {
        internalType: "uint40",
        name: "unlockTime_",
        type: "uint40",
      },
    ],
    name: "createLpLocker",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
      {
        internalType: "uint40",
        name: "unlockTime_",
        type: "uint40",
      },
    ],
    name: "createTokenLocker",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "creationEnabled",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint40",
        name: "id_",
        type: "uint40",
      },
    ],
    name: "getLpData",
    outputs: [
      {
        internalType: "bool",
        name: "hasLpData",
        type: "bool",
      },
      {
        internalType: "uint40",
        name: "id",
        type: "uint40",
      },
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "balance0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "balance1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "price0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "price1",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint40",
        name: "id_",
        type: "uint40",
      },
    ],
    name: "getLpLockAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint40",
        name: "id_",
        type: "uint40",
      },
    ],
    name: "getLpLockData",
    outputs: [
      {
        internalType: "bool",
        name: "isLpToken",
        type: "bool",
      },
      {
        internalType: "uint40",
        name: "id",
        type: "uint40",
      },
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "lockOwner",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "createdBy",
        type: "address",
      },
      {
        internalType: "uint40",
        name: "createdAt",
        type: "uint40",
      },
      {
        internalType: "uint40",
        name: "blockTime",
        type: "uint40",
      },
      {
        internalType: "uint40",
        name: "unlockTime",
        type: "uint40",
      },
      {
        internalType: "uint256",
        name: "balance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalSupply",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "address_",
        type: "address",
      },
    ],
    name: "getLpLockersForAddress",
    outputs: [
      {
        internalType: "uint40[]",
        name: "",
        type: "uint40[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint40",
        name: "id_",
        type: "uint40",
      },
    ],
    name: "getTokenLockAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint40",
        name: "id_",
        type: "uint40",
      },
    ],
    name: "getTokenLockData",
    outputs: [
      {
        internalType: "bool",
        name: "isLpToken",
        type: "bool",
      },
      {
        internalType: "uint40",
        name: "id",
        type: "uint40",
      },
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "lockOwner",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "createdBy",
        type: "address",
      },
      {
        internalType: "uint40",
        name: "createdAt",
        type: "uint40",
      },
      {
        internalType: "uint40",
        name: "blockTime",
        type: "uint40",
      },
      {
        internalType: "uint40",
        name: "unlockTime",
        type: "uint40",
      },
      {
        internalType: "uint256",
        name: "balance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalSupply",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "address_",
        type: "address",
      },
    ],
    name: "getTokenLockersForAddress",
    outputs: [
      {
        internalType: "uint40[]",
        name: "",
        type: "uint40[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lpLockerCount",
    outputs: [
      {
        internalType: "uint40",
        name: "",
        type: "uint40",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint40",
        name: "id_",
        type: "uint40",
      },
      {
        internalType: "address",
        name: "newOwner_",
        type: "address",
      },
      {
        internalType: "address",
        name: "previousOwner_",
        type: "address",
      },
      {
        internalType: "address",
        name: "createdBy_",
        type: "address",
      },
    ],
    name: "notifyLpLockerOwnerChange",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint40",
        name: "id_",
        type: "uint40",
      },
      {
        internalType: "address",
        name: "newOwner_",
        type: "address",
      },
      {
        internalType: "address",
        name: "previousOwner_",
        type: "address",
      },
      {
        internalType: "address",
        name: "createdBy_",
        type: "address",
      },
    ],
    name: "notifyTokenLockerOwnerChange",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "value_",
        type: "bool",
      },
    ],
    name: "setCreationEnabled",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "tokenLockerCount",
    outputs: [
      {
        internalType: "uint40",
        name: "",
        type: "uint40",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITokenLockerManagerV1__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenLockerManagerV1Interface {
    return new Interface(_abi) as ITokenLockerManagerV1Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITokenLockerManagerV1 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ITokenLockerManagerV1;
  }
}
